name: Build Windows Executable

on: [push]

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install pygame pyinstaller

      - name: Build executable
        run: |
          pyinstaller --noconsole --onefile --add-data "assets;assets" --name "GuardiaoDoIgarape" main.py

      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: Executavel_Windows
          path: dist/GuardiaoDoIgarape.exe
